from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
LOG_DIR = BASE_DIR / "logs"
DB_PATH = DATA_DIR / "market.db"

BINANCE_BASE_URL = "https://api.binance.com"
HTTP_TIMEOUT = 10
HTTP_RETRY = 3
HTTP_RETRY_BACKOFF = 1.5

DEFAULT_SYMBOL = "ETHUSDT"
DEFAULT_INTERVAL = "1h"
DEFAULT_KLINES_LIMIT = 500

MONITOR_POLL_SECONDS = 10
PCT_CHANGE_ALERT = 1.0
PRICE_UPPER_ALERT: float | None = None
PRICE_LOWER_ALERT: float | None = None

BACKTEST_FAST_MA = 10
BACKTEST_SLOW_MA = 30
BACKTEST_INITIAL_CAPITAL = 10_000.0
BACKTEST_FEE_RATE = 0.001

TRADE_CAPITAL = 1000.0
TRADE_LEVERAGE = 20
TRADE_RISK_PER_TRADE = 2.0
TRADE_STOP_LOSS_PCT = 2.0
TRADE_TAKE_PROFIT_PCT = 4.0
TRADE_CHECK_INTERVAL = 30
